---
- name: My Super Playbook
  hosts: all
  become: yes

  vars: 
   mytext: "Privet ot Turm@n"

  tasks:
  - name: Ping test
    ping:

  - include: create_folders.yml
  - include: create_files.yml

