---
- name: Playbook for Variables Lesson
  hosts: all
  become: yes

  vars:
    message1: Privet
    message2: World
    secret  : NJJBHBLKMNHKJN

  tasks:
  
  - name: Print Secret variable
    debug: 
      var: secret
             
  - debug: 
      msg: "Secretnoe slovo: {{ secret }}"

 # - debug:
 #     msg: "Vladelec Etogo Servera -->{{ owner}}<--"

#  - set_fact: full_message="{{ message1 }} {{ message2 }} from {{ owner }}"

  - debug:
      var: full_message

  - debug:
     var: ansible_distribution
 
  - shell: uptime
    register: results

  - debug:
      var: results.stdout

#  - shell: timedatectl set-timezone=Europe/Kiev
#    register: results2
 
#  - debug:
#      var: results2.stdout
