---
- name: Ansible lesson ERRORS
  hosts: all
  any_errors_fatal: true
  become: true

  


  tasks:
  - name: Task Number 1
    apt: name=tree state=latest
    ignore_errors: yes

  - name: Task Number 2
    shell: echo "Hello world" 
    register: results
    failed_when: results.rc == 0
